create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  client_name text not null,
  product text not null,
  qty numeric not null default 0,
  price numeric not null default 0,
  cost numeric not null default 0,
  total numeric not null default 0,
  paid numeric not null default 0,
  date text not null,
  status text not null default 'unpaid',
  created_at timestamp with time zone not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id) on delete cascade,
  client_name text not null,
  amount numeric not null default 0,
  date text not null,
  note text,
  created_at timestamp with time zone not null default now()
);
